name: my First workflow

on: [push]

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Welcome to my first workflow 
        run: echo "Hello World"
      - name: Lists files in the current directory
        run: ls 
      - name: read the readme file
        run: cat README.md
