name: my First workflow

on: [push]

jobs:
  fisrst-workflow:
    runs-on: ubuntu-latest
    steps:
        - name: Welcome to my first workflow 
          run: echo "Hello World"
        - name: Lists files in the current directory
          run: ls -la
        - name: read the readme file
          run: cat readme.md
   