name: my First workflow

on: [push]

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Welcome to my first workflow 
        run: |
         echo "Hello World"
         ls 
         cat README.md

      